export default {
    tab_black_text: "#312807",
    grey_text: "#d3d3d3",
    wsp_bg: "#effbf0",
    fb_bg: "#eff4fb",
    yt_bg: "#fbefef",
    istg_bg: "#fbeff7",
    dribble_bg: "#fbeff3",
    view_all_bg: "#cbe6ff",
    border_link: "#fbcc25",
    bg_link: "#f8f8ef",
    dec_border_link: "#f1f1f1",
    theme: "#faf9f7",
    search_bar_text: "#969696",
    white: "#fff",
    black: "#000",
    view_text_color: "#2c81cd",
    sn_text_color: "#343434",
    videoPicTextColor: "#161616",
    videoPicSndTextColor: "#5a5a5a"
}